# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: app
          image: sekarfeb/react-hello-app:latest
          ports:
            - containerPort: 3000
---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: react-app 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer # Use the appropriate service type for your environment
  loadBalancerIP: ${LB_IP}
